### ISSUE TITLE
docker pull hyperledger/vehicle-manufacture-vda ERROR

### ISSUE THREAD

**Issue by WiwiC** [hyperledger/composer-sample-applications#119] opened 2018-03-09 13:50 UTC
I'm trying to run locally the composer-sample-applications vehicle-manufacture and I have an issue after executing the command _cat installers/hlfv1/install.sh | bash_ I have an error saying  hyperledger/vehicle-manufacture-vda:latest not found.

Any idea how to fix this ?

Here is a copy and paste of my terminal screen.

Thank you very much.

> williams-mbp:vehicle-manufacture be07993$ ./build.sh
> 
> Grab the directory containing this script.
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
>  cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd 
>  dirname "${BASH_SOURCE[0]}" 
> cd "${DIR}/installers"
> 
> if [ -z ${DEMO_FABRIC_VERSION+x} ]; then
>  echo "FABRIC_VERSION is unset, assuming hlfv1"
>  export DEMO_FABRIC_VERSION="hlfv1"
> else
>  echo "DEMO_FABRIC_VERSION is set to '$DEMO_FABRIC_VERSION'"
> fi
> FABRIC_VERSION is unset, assuming hlfv1
> 
> clean up
> rm -rf $DEMO_FABRIC_VERSION/fabric-dev-servers/
> rm -f fabric-dev-servers.zip
> 
> Get the fabric tools
> curl -O https://raw.githubusercontent.com/hyperledger/composer-tools/master/packages/fabric-dev-servers/fabric-dev-servers.zip
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  133k  100  133k    0     0   187k      0 --:--:-- --:--:-- --:--:--  187k
> 
> Build all of the installers.
> unzip -q fabric-dev-servers.zip -d $DEMO_FABRIC_VERSION/fabric-dev-servers/
> $DEMO_FABRIC_VERSION/build.sh
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
>  cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd 
>  dirname "${BASH_SOURCE[0]}" 
> 
> ROOT=$DIR/../..
> 
> cd $ROOT
> npm install
> updated 1 package in 0.764s
> 
> cd "${DIR}"
> cat install.sh.in | sed \
>     -e 's/{{COMPOSER-VERSION}}/latest/g' \
>     -e 's/{{VEHICLE-MANUFACTURE-VERSION}}/latest/g' \
>     -e 's/{{NODE-RED-VERSION}}/latest/g' \
>     > install.sh
> echo "PAYLOAD:" >> install.sh
> tar czf - -C $ROOT/node_modules/vehicle-manufacture-network/dist vehicle-manufacture-network.bna -C $DIR flows.json fabric-dev-servers >> install.sh
> 
> cd $ROOT
> npm install vehicle-manufacture-network@unstable --no-save
> + vehicle-manufacture-network@0.2.2-20180301135319
> updated 1 package in 1.185s
> 
> cd "${DIR}"
> cat install.sh.in | sed \
>     -e 's/{{COMPOSER-VERSION}}/unstable/g' \
>     -e 's/{{VEHICLE-MANUFACTURE-VERSION}}/unstable/g' \
>     -e 's/{{NODE-RED-VERSION}}/unstable/g' \
>     > install-unstable.sh
> echo "PAYLOAD:" >> install-unstable.sh
> tar czf - -C $ROOT/node_modules/vehicle-manufacture-network/dist vehicle-manufacture-network.bna -C $DIR flows.json fabric-dev-servers >> install-unstable.sh
> 
> clean up
> rm -rf $DEMO_FABRIC_VERSION/fabric-dev-servers/
> rm -f fabric-dev-servers.zip
> williams-mbp:vehicle-manufacture be07993$ cat installers/hlfv1/install.sh | bash
> 
> Docker stop function
> function stop()
> {
> P1=$(docker ps -q)
> if [ "${P1}" != "" ]; then
>   echo "Killing all running containers"  &2> /dev/null
>   docker kill ${P1}
> fi
> 
> P2=$(docker ps -aq)
> if [ "${P2}" != "" ]; then
>   echo "Removing all containers"  &2> /dev/null
>   docker rm ${P2} -f
> fi
> }
> 
> if [ "$1" == "stop" ]; then
>  echo "Stopping all Docker containers" >&2
>  stop
>  exit 0
> fi
> 
> Get the current directory.
> DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
> cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
> dirname "${BASH_SOURCE[0]}"
> 
> Get the full path to this script.
> SOURCE="${DIR}/composer.sh"
> 
> Create a work directory for extracting files into.
> WORKDIR="$(pwd)/composer-data-latest"
> pwd
> rm -rf "${WORKDIR}" && mkdir -p "${WORKDIR}"
> cd "${WORKDIR}"
> 
> Find the PAYLOAD: marker in this script.
> PAYLOAD_LINE=$(grep -a -n '^PAYLOAD:$' "${SOURCE}" | cut -d ':' -f 1)
> grep -a -n '^PAYLOAD:$' "${SOURCE}" | cut -d ':' -f 1
> echo PAYLOAD_LINE=${PAYLOAD_LINE}
> PAYLOAD_LINE=253
> 
> Find and extract the payload in this script.
> PAYLOAD_START=$((PAYLOAD_LINE + 1))
> echo PAYLOAD_START=${PAYLOAD_START}
> PAYLOAD_START=254
> tail -n +${PAYLOAD_START} "${SOURCE}" | tar -xzf -
> 
> Ensure sensible permissions on the extracted files.
> find . -type d | xargs chmod a+rx
> find . -type f | xargs chmod a+r
> 
> Pull the latest versions of all the Docker images.
> docker pull hyperledger/composer-playground:latest
> latest: Pulling from hyperledger/composer-playground
> Digest: sha256:83640c09c3d72b1cfcc1ffb6b4c91d19d0e0784b89f2c17dd6fc463b91583533
> Status: Image is up to date for hyperledger/composer-playground:latest
> docker pull hyperledger/composer-cli:latest
> latest: Pulling from hyperledger/composer-cli
> Digest: sha256:08d3a2c78cdead8ab72b8969c002fe4d6152ed6decde85edd3648c188ea56b9b
> Status: Image is up to date for hyperledger/composer-cli:latest
> docker pull hyperledger/composer-rest-server:latest
> latest: Pulling from hyperledger/composer-rest-server
> Digest: sha256:3a2192af94270effe00459663dc69892ffd4d24a31ee46684d74ffee54d109da
> Status: Image is up to date for hyperledger/composer-rest-server:latest
> docker pull hyperledger/vehicle-manufacture-vda:latest
> **Error response from daemon: manifest for hyperledger/vehicle-manufacture-vda:latest not found**

**Comment by awjh-ibm** [comment] 2018-03-13 10:30
Hi @WiwiC,I think the issue is that the install script has been updated in the git repo however we have yet to release, this means that, as we have renamed from vehicle-lifecycle to vehicle-manufacture, the docker images of the correct names do not yet exist. This issue should hopefully be solved once we release.

**Comment by davidkel** [comment] 2018-09-04 06:41
This issue should now be resolved, closing

**Closed by davidkel** 2018-09-04 06:41 UTC
